# @name GetStudents
GET http://localhost:3000/students

###

# @name PostAssociateStudent
POST http://localhost:3000/student/9a869c14-c6d0-4680-aaac-c2e7c7db6667



###

# @name GetTeacher
GET http://localhost:3000/teachers

###

# @name GetExercise
GET http://localhost:3000/exercises

###

# @name GetWorkout
GET http://localhost:3000/workouts